# Pipeline 1 - Dates Matching

The first pipeline will automate the following actions.<br>
INPUTS: 
* AOI
* PERIOD
* OUTPUT FOLDER (output will be organized by AOI)

ACTIONS:
1. Open the AOI
2. Create the S2 dataframe with cloud cover for the AOI and dates
3. Create the SWOT dataframe with the possible mosaics
4. Match SWOT and S2 dates, ordered by cloud cover
5. Create output structure in the AOI folder (/ref_masks, /OPERA, /dataframes)

## Imports

In [19]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

from swot_toolkit.pipe1 import prepare_aoi_dataframes
from swot_toolkit.swot import auth_earthaccess

auth_earthaccess()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Pipeline 1

In [20]:
REGION = "Rio_Madeira"
DATE_RANGE = ("2024-01-01", "2025-09-30")
OUTPUT_DIR = "/data/swot/output/"

In [21]:
aoi_path = Path("/data/swot/AOIs/") / f"{REGION}.kml"

In [ ]:
output_dir = prepare_aoi_dataframes(aoi_path, DATE_RANGE, OUTPUT_DIR)

## Analyze results

In [22]:
from pathlib import Path

import pandas as pd

from swot_toolkit.kml import read_kml_geometry
from swot_toolkit.pipe1 import generate_s2_figs_from_mosaic

In [23]:
output_dir = Path(OUTPUT_DIR) / REGION
output_dir

PosixPath('/data/swot/output/Rio_Madeira')

In [24]:
# Open the matches between S2 and SWOT
matches = pd.read_parquet(output_dir / "dfs/swot_s2_matches.parquet")
matches.sort_values("valid_pxls", ascending=False).iloc[:10]

                        date                datetime   tile  valid_pxls OPERA
swot_mosaic_date
2024-08-21        2024-08-24 2024-08-24 14:17:11.024  20MRV    0.996669   S2A
2024-08-11        2024-08-09 2024-08-09 14:17:19.024  20MRV    0.996104   S2B
2024-08-21        2024-08-19 2024-08-19 14:17:09.024  20MRV    0.995886   S2B
2025-07-21        2025-07-20 2025-07-20 14:21:01.024  20MRV    0.995181   S2C
2024-06-19        2024-06-20 2024-06-20 14:17:19.024  20MRV    0.989063   S2B
2025-07-21        2025-07-22 2025-07-22 14:20:51.024  20MRV    0.985348   S2A
2024-08-11        2024-08-14 2024-08-14 14:17:11.024  20MRV    0.985189   S2A
2024-07-10        2024-07-05 2024-07-05 14:17:11.024  20MRV    0.971893   S2A
2024-09-11        2024-09-08 2024-09-08 14:17:09.024  20MRV    0.968684   S2B
2025-07-21        2025-07-25 2025-07-25 14:17:09.024  20MRV    0.915941   S2B

In [32]:
mosaics = pd.read_parquet(output_dir / "dfs/swot_raster_results.parquet")
mosaics.head()

                      cycle_id pass_id tile_id         date_str     vers  \
mosaic_date tile_name
2024-01-05  089_073F       009     089    073F  20240107T072551  PIC0_01
            548_082F       008     548    082F  20240102T201755  PIC0_01
2024-01-25  089_073F       010     089    073F  20240128T041057  PIC0_01
            548_082F       009     548    082F  20240123T170300  PIC0_01
2024-02-15  089_073F       011     089    073F  20240218T005602  PIC0_01

                                 datetime        date  \
mosaic_date tile_name
2024-01-05  089_073F  2024-01-07 07:25:51  2024-01-07
            548_082F  2024-01-02 20:17:55  2024-01-02
2024-01-25  089_073F  2024-01-28 04:10:57  2024-01-28
            548_082F  2024-01-23 17:03:00  2024-01-23
2024-02-15  089_073F  2024-02-18 00:56:02  2024-02-18

                                                               native-id  \
mosaic_date tile_name
2024-01-05  089_073F   SWOT_L2_HR_Raster_100m_UTM21M_N_x_x_x_009_089_...
            548_082F   SWOT_L2_HR_Raster_100m_UTM20M_N_x_x_x_008_548_...
2024-01-25  089_073F   SWOT_L2_HR_Raster_100m_UTM21M_N_x_x_x_010_089_...
            548_082F   SWOT_L2_HR_Raster_100m_UTM20M_N_x_x_x_009_548_...
2024-02-15  089_073F   SWOT_L2_HR_Raster_100m_UTM21M_N_x_x_x_011_089_...

                                                                     url
mosaic_date tile_name
2024-01-05  089_073F   https://archive.swot.podaac.earthdata.nasa.gov...
            548_082F   https://archive.swot.podaac.earthdata.nasa.gov...
2024-01-25  089_073F   https://archive.swot.podaac.earthdata.nasa.gov...
            548_082F   https://archive.swot.podaac.earthdata.nasa.gov...
2024-02-15  089_073F   https://archive.swot.podaac.earthdata.nasa.gov...

### Choose a mosaic date to check the S2 items (figs generated in output dir)

In [43]:
MOSAIC_DATE = "2024-08-21"

aoi = read_kml_geometry(aoi_path)[0]
s2_matches = generate_s2_figs_from_mosaic(
    MOSAIC_DATE,
    matches,
    aoi,
    output_dir,
)

s2_matches

Saving figure S2A_MSIL2A_20240824T141711_R010_T20MRV_20240824T195549_thumb.png...
Saving figure S2B_MSIL2A_20240819T141709_R010_T20MRV_20240819T182149_thumb.png...

                        date                datetime   tile  valid_pxls OPERA
swot_mosaic_date
2024-08-21        2024-08-19 2024-08-19 14:17:09.024  20MRV    0.995886   S2B
2024-08-21        2024-08-24 2024-08-24 14:17:11.024  20MRV    0.996669   S2A

### Selection of Ref S2 img

In [46]:
s2_id = "S2B_MSIL2A_20240819T141709_R010_T20MRV_20240819T182149"

In [47]:
from swot_toolkit.pipe1 import create_date_subfolder

create_date_subfolder(output_dir, MOSAIC_DATE, s2_id)

PosixPath('/data/swot/output/Rio_Madeira/2024-08-21')