# Pipeline 1 - Dates Matching

The first pipeline will automate the following actions.<br>
INPUTS: 
* AOI
* PERIOD
* OUTPUT FOLDER (output will be organized by AOI)

ACTIONS:
1. Open the AOI
2. Create the S2 dataframe with cloud cover for the AOI and dates
3. Create the SWOT dataframe with the possible mosaics
4. Match SWOT and S2 dates, ordered by cloud cover
5. Create output structure in the AOI folder (/ref_masks, /OPERA, /dataframes)

## Imports

In [16]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

from swot_toolkit.pipe1 import prepare_aoi_dataframes
from swot_toolkit.swot import auth_earthaccess

auth_earthaccess()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Pipeline 1

In [17]:
REGION = "Northeast"
DATE_RANGE = ("2024-01-01", "2025-09-30")
OUTPUT_DIR = "/data/swot/output/"

In [18]:
aoi_path = Path("/data/swot/AOIs/") / f"{REGION}.kml"

In [19]:
# output_dir = prepare_aoi_dataframes(aoi_path, DATE_RANGE, OUTPUT_DIR)

## Analyze results

In [20]:
from pathlib import Path

import pandas as pd

from swot_toolkit.kml import read_kml_geometry
from swot_toolkit.pipe1 import generate_s2_figs_from_mosaic

In [21]:
output_dir = Path(OUTPUT_DIR) / REGION
output_dir

PosixPath('/data/swot/output/Northeast')

In [26]:
# Open the matches between S2 and SWOT
matches = pd.read_parquet(output_dir / "dfs/swot_s2_matches.parquet")
matches.sort_values("valid_pxls", ascending=False).iloc[:20]

,date,datetime,tile,valid_pxls,OPERA
swot_mosaic_date,,,,,
2025-07-20,2025-07-16,2025-07-16 13:03:11.025,24MWT,0.995740,S2C
2024-05-29,2024-05-27,2024-05-27 13:02:49.024,24MWT,0.995400,S2B
2025-08-10,2025-08-07,2025-08-07 13:03:01.024,24MWT,0.995287,"S2B, S2A"
2025-08-31,2025-08-30,2025-08-30 13:02:49.024,24MWT,0.995172,S2B
2025-04-27,2025-04-27,2025-04-27 13:03:11.025,24MWT,0.995163,S2C
2024-07-09,2024-07-11,2024-07-11 13:02:51.024,24MWT,0.994336,S2A
2024-07-30,2024-07-31,2024-07-31 13:02:51.024,24MWT,0.994185,S2A
2024-12-02,2024-11-28,2024-11-28 13:02:41.024,24MWT,0.993803,S2A
2025-06-08,2025-06-08,2025-06-08 13:03:01.024,24MWT,0.993761,"S2B, S2A"
2024-12-23,2024-12-23,2024-12-23 13:02:49.024,24MWT,0.993156,S2B
2025-02-24,2025-02-21,2025-02-21 13:02:49.024,24MWT,0.990581,S2B
2025-03-17,2025-03-13,2025-03-13 13:02:49.024,24MWT,0.988473,S2B
2025-07-20,2025-07-21,2025-07-21 13:02:49.024,24MWT,0.984244,S2B
2025-07-20,2025-07-18,2025-07-18 13:03:01.024,24MWT,0.981792,"S2B, S2A"
2025-09-14,2025-09-16,2025-09-16 13:03:01.024,24MWT,0.976716,"S2B, S2A"
2024-08-20,2024-08-20,2024-08-20 13:02:41.025,24MWT,0.972996,S2A
2024-11-12,2024-11-08,2024-11-08 13:02:41.024,24MWT,0.969940,S2A
2024-08-20,2024-08-15,2024-08-15 13:02:49.024,24MWT,0.967098,S2B
2024-12-23,2024-12-18,2024-12-18 13:02:41.024,24MWT,0.948197,S2A
2024-06-19,2024-06-16,2024-06-16 13:02:49.024,24MWT,0.944049,S2B

In [53]:
# mosaics = pd.read_parquet(output_dir / "dfs/swot_raster_results.parquet")
# mosaics.head()

### Choose a mosaic date to check the S2 items (figs generated in output dir)

In [28]:
MOSAIC_DATE = "2024-05-29"

aoi = read_kml_geometry(aoi_path)[0]
s2_matches = generate_s2_figs_from_mosaic(
    MOSAIC_DATE,
    matches,
    aoi,
    output_dir,
)

s2_matches

Saving figure S2A_MSIL2A_20240601T130251_R095_T24MWT_20240601T203855_thumb.png...
Saving figure S2A_MSIL2A_20240529T125311_R052_T24MWT_20240529T201932_thumb.png...
Saving figure S2B_MSIL2A_20240527T130249_R095_T24MWT_20240527T181925_thumb.png...
Saving figure S2B_MSIL2A_20240524T125309_R052_T24MWT_20240524T181204_thumb.png...

                        date                datetime   tile  valid_pxls OPERA
swot_mosaic_date
2024-05-29        2024-05-24 2024-05-24 12:53:09.024  24MWT    0.274258   S2B
2024-05-29        2024-05-27 2024-05-27 13:02:49.024  24MWT    0.995400   S2B
2024-05-29        2024-05-29 2024-05-29 12:53:11.024  24MWT    0.122921   S2A
2024-05-29        2024-06-01 2024-06-01 13:02:51.024  24MWT    0.568770   S2A

### Selection of Ref S2 img

In [29]:
s2_id = "S2B_MSIL2A_20240527T130249_R095_T24MWT_20240527T181925"

In [30]:
from swot_toolkit.pipe1 import create_date_subfolder

create_date_subfolder(output_dir, MOSAIC_DATE, s2_id)

PosixPath('/data/swot/output/Northeast/2024-05-29')